apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: games-hpa
  namespace: techchallenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: games
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
