apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: techchallenge
type: Opaque
stringData:
  USERS_DB: "Server=mssql;Database=UsersDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
  GAMES_DB: "Server=mssql;Database=GamesDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
  PAYMENTS_DB: "Server=mssql;Database=PaymentsDb;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;"
